export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const SEARCHING_DATA_REQUEST = "SERACHING_DATA_REQUEST";
export const SEARCHING_DATA_SUCCESS = "SEARCHING_DATA_SUCCESS";
export const SEARCHING_DATA_FAILURE = "SEARCHING_DATA_FAILURE";

export const RESENTMOVIE_DATA_REQUEST = "RESENTMOVIE_DATA_REQUEST";
export const RESENTMOVIE_DATA_SUCCESS = "RESENTMOVIE_DATA_SUCCESS";
export const RESENTMOVIE_DATA_FAILURE = "RESENTMOVIE_DATA_FAILURE";

export const SIMILIARE_DATA_REQUEST = "SIMILIARE_DATA_REQUEST";
export const SIMILIARE_DATA_SUCCESS = "SIMILIARE_DATA_SUCCESS";
export const SIMILIARE_DATA_FAILURE = "SIMILIARE_DATA_FAILURE";