export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const SEARCHING_DATA_REQUEST = "SERACHING_DATA_REQUEST";
export const SEARCHING_DATA_SUCCESS = "SEARCHING_DATA_SUCCESS";
export const SEARCHING_DATA_FAILURE = "SEARCHING_DATA_FAILURE";